# Generated by Django 4.2.4 on 2023-08-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cervezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilos', models.CharField(max_length=50)),
                ('colores', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Espumantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=50)),
                ('brutNature', models.CharField(max_length=50)),
                ('extraBrut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spirits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vodka', models.CharField(max_length=50)),
                ('gin', models.CharField(max_length=50)),
                ('ron', models.CharField(max_length=50)),
                ('licor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tintos', models.CharField(max_length=50)),
                ('blancos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Whiskies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blends', models.CharField(max_length=50)),
                ('singleMalts', models.CharField(max_length=50)),
            ],
        ),
    ]
