# Generated by Django 4.2.4 on 2023-08-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_cervezas_cerveza_rename_espumantes_espumante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cerveza',
            old_name='colores',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='cerveza',
            old_name='estilos',
            new_name='estilo',
        ),
        migrations.RenameField(
            model_name='espumante',
            old_name='brutNature',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='espumante',
            old_name='extraBrut',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='espumante',
            old_name='nature',
            new_name='varietal',
        ),
        migrations.RenameField(
            model_name='spirit',
            old_name='gin',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='spirit',
            old_name='licor',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='spirit',
            old_name='ron',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='vino',
            old_name='blancos',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='vino',
            old_name='tintos',
            new_name='uva',
        ),
        migrations.RenameField(
            model_name='whisky',
            old_name='blends',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='whisky',
            old_name='singleMalts',
            new_name='marca',
        ),
        migrations.RemoveField(
            model_name='spirit',
            name='vodka',
        ),
    ]
