# Generated by Django 4.2.4 on 2023-08-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_rename_colores_cerveza_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.CharField(max_length=1000)),
            ],
        ),
    ]
